#!/usr/bin/env bash
# Display information about subdomains

display_info() {
    local domain="$1"
    local subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        dig_output=$(dig "$sub.$domain" +short)
        echo "The subdomain $sub is a A record and points to $dig_output"
    done
}

if [ "$#" -eq 1 ]; then
    display_info "$1"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
fi
