#!/usr/bin/env bash
# Install and configures Nginx web server

sudo apt-get update -y && sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
