#!/usr/bin/env bash
# Install and configures Nginx web server

sudo apt-get update -y -qq && sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo -e "Hello World!" | dd status=none of=/var/www/html/index.html
sudo service nginx restart
