#!/usr/bin/env bash
# Configure Nginx server to redirect /redirect_me to another page

sudo apt-get update -y
sudo apt-get install -y nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo tee -a /etc/nginx/sites-available/default <<EOF
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF
sudo service nginx restart
