#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

add_nginx_config() {
    sudo sed -i "/^}$/i $1" /etc/nginx/sites-available/default
}
sudo apt-get update -y && sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
add_nginx_config "location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"
add_nginx_config "location @404 { return 404 'Ceci n\\'est pas une page\\n'; }"
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo service nginx restart
