#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
    listen 80 default_server;
    server_name _;
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/custom_404
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/custom_404
service nginx restart || /etc/init.d/nginx restart
