#!/usr/bin/env bash
# Install and configures HAProxy as a load balancer
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i '/^frontend http_front/,/^$/c \frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tmode http\n\tbalance roundrobin\n\tserver 529658-web-01 54.197.50.4:80 check\n\tserver 529658-web-02 34.229.137.21:80 check' /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
