#!/usr/bin/env bash
# Configures Nginx to listen on port 80
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
sudo sleep 2
sudo service nginx status | grep "not running" >/dev/null && sudo service nginx start
