#!/usr/bin/env bash
# Configures Nginx to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default && service nginx restart && sleep 2 && service nginx status | grep "not running" >/dev/null && service nginx start
