#!/usr/bin/env bash
# stop the 4-to_infinity_and_beyond process
pid=$(pgrep -o "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    echo "Stopping process $pid"
    kill "$pid"
else
    echo "Process not found"
fi
