#!/usr/bin/env bash
# display "Best School" 10 times, "Hi" on the 9

count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
