#!/usr/bin/env bash
# display time for 12h & 59m

hour=0
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    for ((minute=1; minute<=59; minute++)); do
        echo $minute
    done
    ((hour++))
done
