#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user
sudo service nginx stop
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
